name: hYdra2 CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-24.04

          - name: Windows x64
            os: windows-2022

          - name: macOS
            os: macos-15

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.11.2'
          target: desktop
          modules: 'qtgraphs'
          cache: true

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/stage"
          -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build --build-config Release --output-on-failure

      - name: Install and deploy
        run: cmake --install build --config Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: hYdra2-${{ matrix.name }}
          path: stage/
          if-no-files-found: error
          retention-days: 7
